import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { SiteHeader } from "@/app/components/SiteHeader";
import { SiteFooter } from "@/app/components/SiteFooter";
import { SiteWhatsappButton } from "@/app/components/SiteWhatsappButton";
import { LeadFormsProvider } from "@/app/components/marketing/LeadFormsProvider";
import { FacebookPixelRoot } from "@/app/components/marketing/FacebookPixelRoot";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/files/glow-skin-emblem-gs-initials.png",
    apple: "/files/glow-skin-emblem-gs-initials.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LeadFormsProvider>
          <FacebookPixelRoot />
          <SiteHeader />
          <main className="flex-1 w-full min-h-0">{children}</main>
          <SiteFooter />
          <SiteWhatsappButton />
        </LeadFormsProvider>
        <Script
          id="metricool-be"
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{
            __html:
              'function loadScript(a){var b=document.getElementsByTagName("head")[0],c=document.createElement("script");c.type="text/javascript",c.src="https://tracker.metricool.com/resources/be.js",c.onreadystatechange=a,c.onload=a,b.appendChild(c)}loadScript(function(){beTracker.t({hash:"3233026e425033af24d3c672ce991559"})});',
          }}
        />
      </body>
    </html>
  );
}
